### ISSUE TITLE
[BUG] State from Dags with failed tasks should't be success

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/airflow-kubernetes#101]
We're marking as succeeded Dags with failed tasks. We should evaluate the task results in order to set the final status of the Dag correctly.

This misbehaviour is leading to confusion and lot of human intervention to double check the actual status of tasks within a certain Dags, and it's becoming unsustainable due to the big amount of Dags.

**Comment by Harshith-umesh** [comment]
fixed with https://github.com/cloud-bulldozer/airflow-kubernetes/pull/125
