### ISSUE TITLE
Upgrade tests are trying to upgrade cluster to same version

### ISSUE THREAD

**Issue by amitsagtani97** [cloud-bulldozer/airflow-kubernetes#124]
Considering 4.10 is the latest version in the CI

Expected behavior - 
Upgrade an Openshift 4.9 stable release to the latest 4.10 nightly version.

Current Behaviour - 
Upgrading Openshift 4.10 latest nightly to the same 4.10 version, hence no upgrade takes place and it always passes with no metrics.

Solutions - 
- At the last step after cleanup, deploy a cluster with the previous stable version and then upgrade it to the latest nightly.
OR
- Disable upgrade test in the most recent Openshift version.

**Comment by Harshith-umesh** [comment]
closed with this PR: https://github.com/cloud-bulldozer/airflow-kubernetes/pull/163
