### ISSUE TITLE
Migrate release_stream_base_url

### ISSUE THREAD

**Issue by afcollins** [cloud-bulldozer/airflow-kubernetes#295]
The current release_stream_base_url of *.openshiftapps.com is a route to a specific cluster behind the VPN.

There is a simpler endpoint that is easier to template for AMD and ARM binaries, which follows the format:
https://amd64.ocp.releases.ci.openshift.org/
https://arm64.ocp.releases.ci.openshift.org/

The REST endpoints are the same. We should migrate to use the new routes.

**Comment by rsevilla87** [comment]
Sounds good!, some code changes will be required though.
